version: '3'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: diplomski-open-ldap
    environment:
      LDAP_ORGANISATION: "Diplomski"
      LDAP_DOMAIN: "diplomski.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap:/var/lib/ldap
      - ./slapd.d:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: myphpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

  guacamole-mysql:
    image: mysql:5.7
    container_name: guacamole-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  keycloak-mysql:
    image: mysql:8.0
    container_name: keycloak-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak_password
    volumes:
      - ./keycloak-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  guacamole-init:
    image: guacamole/guacamole
    container_name: guacamole-init
    environment:
      MYSQL_HOSTNAME: guacamole-mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
    depends_on:
      guacamole-mysql:
        condition: service_healthy
    command: /opt/guacamole/bin/initdb.sh --mysql > /opt/guacamole/init/initdb.sql
    volumes:
      - ./init:/opt/guacamole/init

  mysql-client:
    image: mysql:5.7
    container_name: mysql-client
    depends_on:
      guacamole-init:
        condition: service_completed_successfully
      guacamole-mysql:
        condition: service_healthy
    command: >
      /bin/sh -c "
        until mysql -h guacamole-mysql -u guacamole_user -pguacamole_password guacamole_db < /opt/guacamole/init/initdb.sql; do
          echo 'Waiting for MySQL server to be ready...';
          sleep 5;
        done;
        echo 'Guacamole database initialized successfully.';
      "
    volumes:
      - ./init:/opt/guacamole/init

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole-mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
      GUACAMOLE_HOME: /config
    volumes:
      - ./guacamole_config:/config
    depends_on:
      mysql-client:
        condition: service_completed_successfully
      guacd:
        condition: service_started
      openldap:
        condition: service_started

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - guacamole

  guacd:
    image: guacamole/guacd
    container_name: guacd
    ports:
      - "4822:4822"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KC_HTTP_RELATIVE_PATH: /auth
      QUARKUS_DATASOURCE_JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      QUARKUS_DATASOURCE_DB_KIND: mysql
      QUARKUS_DATASOURCE_DB_VERSION: 5.7.0
    ports:
      - "8081:8080"
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    command: 
      - start-dev
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
